language: php

php:
  - 5.6
  - 7.0

notifications:
  email:
    recipients:
      - darkrewrite@gmail.com
    on_success: always
    on_failure: always

before_script:
  - composer install
  - cd tests

script: phpunit -c phpunit.xml